server:
  port: 9090

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:oracle:thin:@//127.0.0.1:1521/xe
    hikari:
      username: sky
      password: java$!

mybatis:
  mapper-locations: classpath*:/mybatis/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
